export const envs = {
  TOKEN_FACTORY_ADDRESS:
    process.env.NEXT_PUBLIC_PUMP_CONTRACT_ADDRESS_ARBITRUM!,
  USDT_ADDRESS: process.env.NEXT_PUBLIC_USDT_ADDRESS_ARBITRUM!,
  SCAN_URL: process.env.NEXT_PUBLIC_ARBITRUM_SCAN_URL!,
  CONTRACT_ROUTER_ADDRESS: process.env.NEXT_PUBLIC_CONTRACT_ROUTER!,
  RAINLAUNCH_URL: process.env.NEXT_PUBLIC_RAINLAUNCH_URL!,
  RAINBOOST_URL: process.env.NEXT_PUBLIC_RAINBOOST_URL!,
  RAINDROP_URL: process.env.NEXT_PUBLIC_RAINDROP_URL!,
  X_URL: process.env.NEXT_PUBLIC_X_URL!,
  DISCORD_URL: process.env.NEXT_PUBLIC_DISCORD_URL!,
  // MODE: process.env.NEXT_PUBLIC_MODE!,
};
