name: Deploy develop
run-name: ${{ github.actor }} is deploying develop branch🚀
on:
  push:
    branches:
      - "develop"
jobs:
  Deploy:
    runs-on: ["rainpump-fe-dev-227"]
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Clean next
        run: |
          rm -rf .next
      
      - name: Copy environment
        run: |
          cp .env.development .env

      - name: Start build
        run: |
          yarn
          yarn build

      - name: Restart pm2
        run: |
          pm2 restart develop.pm2.json